Policy
AY2021S1-CS2103-T16-2/tp pull request #129
Opened 2020-10-27 12:06 UTC by ijavierja

close #104 #106 #102 #103

2020-10-28 13:01 UTC, Joven-Heng approved these changes
LGTM

2020-10-28 13:04 UTC, WeiJie96 requested changes
Just some small changes

2020-10-28 13:13 UTC, WeiJie96 approved these changes
LGTM

2020-10-28 13:13 UTC, merged

2020-10-30 11:42 UTC, WeiJie96 reviewed
Some comments on code quality, testing and other implementation

2020-10-30 11:42 UTC, WeiJie96 commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +            assert policy != null : "Value stored in address should not be null";
Perhaps the assertion can print "Policy should not be null"
Perhaps we should check policy.getPolicyName() != null and policy.getPolicyDescription() != null as well
and print "Policy name should not be null" and "Policy description should not be null"

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/commands/AddCommandTest.java
Perhaps we should test for adding policy as well

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/ModelManagerTest.java
> -
Perhaps we should test for different policyList -> returns false

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
>      }
Perhaps we should have invalidPolicy test, with both invalid name and description

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +                new AddCommand(expectedPersonWithoutPhone, null));
Perhaps we should have Policy here, as we are testing one field at a time. Same for rest of optional fields missing

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
>      }
Perhaps we should test for missing Policy name prefix

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Perhaps we should have policy here

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
>      }
Perhaps we should test for multiple policy names - last policy name accepted

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +                + PRIORITY_DESC_BOB, new AddCommand(expectedPerson, null));
Perhaps we should have policy here, same for rest of multiple fields

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/parser/AddPolicyCommandParserTest.java
> +    }
Perhaps we can refer to add command parser for some tests
- invalid value: failure
- all fields present success => multiple policy names / policy description - last policy name / policy description accepted

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
> +    public void execute_policyIsDuplicatePolicy() {
Perhaps the method name should have throwsCommandException behind

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/logic/commands/AddPolicyCommandTest.java
> +    }
Perhaps we should have .equals() test

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +
Perhaps we should use HashMap here, as previously commented in PolicyList.java

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +        PolicyList policyList = new PolicyList();
Perhaps we should have standardised names for the tests. Same for the rest of the tests in this file

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +
Perhaps we should test for 
- getPolicy(): E.g. null input, null output (key not present), key present
- equals()

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +        assertFalse(policyList.contains(MISSING_FROM_LIST_POLICY));
Perhaps we should have a positive test

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +    }
Perhaps we should test for null and Duplicate

2020-10-30 11:42 UTC, WeiJie96 commented on src/test/java/seedu/address/model/policy/PolicyListTest.java
> +
Perhaps we should test for null

2020-10-30 11:42 UTC, WeiJie96 commented on src/main/java/seedu/address/model/policy/PolicyList.java
> +        return policies.containsKey(policyName.value);
Perhaps we should requireNonNull
Same for the other contains()

2020-10-30 11:42 UTC, WeiJie96 commented on src/main/java/seedu/address/model/policy/PolicyList.java
Is createNewPolicyList() being used? If it is, we can add it into the PolicyListTest.java